### ISSUE TITLE
feat: ToDoListItem 수정 모드 시 입력값에 따른 완료버튼 예외처리 및 로컬 스토리지 모듈화

### ISSUE THREAD

**Issue by Bsfla** [Wanted-Pre-Onboarding-Team-8/wanted-pre-onboarding-fe-Best-Pratice#7]
- [x] ToDoListItem 수정 모드 시 입력값에 따른 완료버튼 예외처리 
- [x] 로컬 스토리지 모듈화

**Comment by dlwldn** [comment]
1. todoList에서 수정모드일때 input 내용이 0자일때 수정되는것을 막기위해 완료버튼 예외처리를 진행하였습니다.
2. 로컬스토리지 재사용성을 고려하여 따로 분리하여 사용하게 하였습니다.
